declare module '*.css';
declare module '*.module.css';
declare module '*.module.scss';
declare module '*.scss';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.json';
declare module '*.webp'